// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartPark.Data;

#nullable disable

namespace SmartPark.Migrations
{
    [DbContext(typeof(SmartParkContext))]
    [Migration("20251111102649_Administrator")]
    partial class Administrator
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartPark.Models.Administrator", b =>
                {
                    b.Property<int>("AdministratorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdministratorID"));

                    b.Property<string>("AdminName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminPassword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdministratorID");

                    b.ToTable("Administrator", (string)null);
                });

            modelBuilder.Entity("SmartPark.Models.ParkingLot", b =>
                {
                    b.Property<int>("ParkingLotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParkingLotID"));

                    b.Property<int?>("AdministratorID")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ParkingLotID");

                    b.HasIndex("AdministratorID");

                    b.ToTable("Parking Lot", (string)null);
                });

            modelBuilder.Entity("SmartPark.Models.ParkingSpot", b =>
                {
                    b.Property<int>("ParkingSpotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParkingSpotID"));

                    b.Property<int?>("AdministratorID")
                        .HasColumnType("int");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("bit");

                    b.Property<int>("ParkingLotID")
                        .HasColumnType("int");

                    b.HasKey("ParkingSpotID");

                    b.HasIndex("AdministratorID");

                    b.HasIndex("ParkingLotID");

                    b.ToTable("Parking Spot", (string)null);
                });

            modelBuilder.Entity("SmartPark.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationID"));

                    b.Property<int?>("AdministratorID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ParkingSpotID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserSMId")
                        .HasColumnType("int");

                    b.HasKey("ReservationID");

                    b.HasIndex("AdministratorID");

                    b.HasIndex("ParkingSpotID");

                    b.HasIndex("UserSMId");

                    b.ToTable("Reservation", (string)null);
                });

            modelBuilder.Entity("SmartPark.Models.UserSM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdministratorID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdministratorID");

                    b.ToTable("UserSM", (string)null);
                });

            modelBuilder.Entity("SmartPark.Models.ParkingLot", b =>
                {
                    b.HasOne("SmartPark.Models.Administrator", null)
                        .WithMany("ParkingLots")
                        .HasForeignKey("AdministratorID");
                });

            modelBuilder.Entity("SmartPark.Models.ParkingSpot", b =>
                {
                    b.HasOne("SmartPark.Models.Administrator", null)
                        .WithMany("ParkingSpots")
                        .HasForeignKey("AdministratorID");

                    b.HasOne("SmartPark.Models.ParkingLot", "ParkingLot")
                        .WithMany("ParkingSpots")
                        .HasForeignKey("ParkingLotID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParkingLot");
                });

            modelBuilder.Entity("SmartPark.Models.Reservation", b =>
                {
                    b.HasOne("SmartPark.Models.Administrator", null)
                        .WithMany("Reservations")
                        .HasForeignKey("AdministratorID");

                    b.HasOne("SmartPark.Models.ParkingSpot", "ParkingSpot")
                        .WithMany()
                        .HasForeignKey("ParkingSpotID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartPark.Models.UserSM", "UserSM")
                        .WithMany()
                        .HasForeignKey("UserSMId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParkingSpot");

                    b.Navigation("UserSM");
                });

            modelBuilder.Entity("SmartPark.Models.UserSM", b =>
                {
                    b.HasOne("SmartPark.Models.Administrator", null)
                        .WithMany("UserSMs")
                        .HasForeignKey("AdministratorID");
                });

            modelBuilder.Entity("SmartPark.Models.Administrator", b =>
                {
                    b.Navigation("ParkingLots");

                    b.Navigation("ParkingSpots");

                    b.Navigation("Reservations");

                    b.Navigation("UserSMs");
                });

            modelBuilder.Entity("SmartPark.Models.ParkingLot", b =>
                {
                    b.Navigation("ParkingSpots");
                });
#pragma warning restore 612, 618
        }
    }
}
